config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  root 'recipes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
require 'httparty'
class Recipe
    include HTTParty
        
    base_uri 'http://www.recipepuppy.com/api'
    default_params onlyImages: 1

    format :json

    def self.for ( keyword = 'chocolate' )
        get('', query: { q: keyword })['results']
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @search = params[:search] || 'XX6Nil'
    @recipes = Recipe.for(@search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodHunter</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="search">
<%= form_tag recipes_index_path, :method => "get" do %>
<%= label_tag(:search, "")%>
<%= text_field_tag :search, params[:search]%>
<%= submit_tag("search", :name=>nil)%>
<%end%>
<% if@search == "XX6Nil"%>
<h1>^^ Search for recipes ^^</h1>
<%else%>
<% if@recipes.empty?%>
<h1>Oops Recipes for <%=@search%> doesn't exist. </h1>
<% else%>
</div>
<h1>Recipes for <%=@search%> </h1>
<table border = "1">
    <tr>
    <th>Photo</th>
    <th>Title</th>
    <th>Ingredients</th>
    </tr>
    <% @recipes.each do |recipe| %>
    <tr class= <%=cycle('even','odd')%> >
        <td><%= link_to(image_tag(recipe["thumbnail"])) %></td>
        <td><%= link_to(sanitize(recipe["title"]))%></td>
        <td><%= recipe["ingredients"] %></td>
    </tr>   
    <% end %>
</table>
<%end%>
<%end%>


<footer><a href="https://github.com/Ebinu-S/FoodHunter.git">Repository</a>
<P>Connect with me</p>
<p><a href="https://github.com/Ebinu-S" target = "_blank"><i class="fa fa-github" style="font-size:24px"></i> Github </a>&nbsp&nbsp&nbsp 
<a href="https://www.instagram.com/dr.retr0_o/" target = "_blank">Instagram <i class="fa fa-instagram" style="font-size:24px"></i></a> </p>
<p>@Ebinu Suneer</P>  
</footer>